apiVersion: v1
kind: Namespace
metadata:
  name: ray-system
  labels:
    name: ray-system
    managed-by: terraform
---
apiVersion: v1
kind: Namespace
metadata:
  name: jobs
  labels:
    name: jobs
    managed-by: terraform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    managed-by: terraform
